# Generated by Django 3.2.6 on 2021-08-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.CharField(max_length=100)),
                ('pic_description', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('pic_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.description')),
            ],
        ),
    ]
